apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: vaultwarden.home
  namespace: vaultwarden
spec:
  dnsNames:
    - vaultwarden.home
  secretName: vaultwarden.home
  issuerRef:
    name: selfsigned
    kind: ClusterIssuer