---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vaultwarden
  namespace: vaultwarden
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vaultwarden
  template:
    metadata:
      labels:
        app: vaultwarden
    spec:
      containers:
        - name: vaultwarden
          image: vaultwarden/server:1.23.0-arm32v6
          ports:
            - containerPort: 80
          env:
            - name: WEBSOCKET_ENABLED
              value: "true"
            - name: SIGNUPS_ALLOWED
              value: "true"
          volumeMounts:
            - name: vaultwarden-pv-storage
              mountPath: /data
          livenessProbe:
            httpGet:
              path: /
              port: 80
              scheme: HTTP
            initialDelaySeconds: 120
            periodSeconds: 15
            timeoutSeconds: 10
            successThreshold: 1
            failureThreshold: 3
      volumes:
        - name: vaultwarden-pv-storage
          persistentVolumeClaim:
            claimName: vaultwarden-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vaultwarden-pvc
  namespace: vaultwarden
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: Service
metadata:
  name: vaultwarden-svc
  namespace: vaultwarden
  labels:
    app: vaultwarden
spec:
  ports:
    - port: 80
      name: vaultwarden-gui
      targetPort: 80
  selector:
    app: vaultwarden
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: vaultwarden-ingressroute
  namespace: vaultwarden
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`vaultwarden.home`)
      kind: Rule
      services:
        - name: vaultwarden-svc
          port: 80
  tls:
    secretName: vaultwarden.home
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: vaultwarden.home
  namespace: vaultwarden
spec:
  dnsNames:
    - vaultwarden.home
  secretName: vaultwarden.home
  issuerRef:
    name: selfsigned
    kind: ClusterIssuer
