version: '3.2'
services:
  vaultwarden:
    image: vaultwarden/server:1.23.0-arm32v6
    container_name: vaultwarden
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - /Users/marc/projects/lab/vaultwarden:/data/
