version: '3.2'
services:
  traefik:
    image: traefik:v2.5
    container_name: traefik

    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/traefik:/etc/traefik

  nginx:
    image: nginx:latest
    container_name: nginx
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nginx.entrypoints=web"
      - "traefik.http.routers.nginx.rule=Host(`nginx.local.buchardtprivat.de`)"