---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: prometheus-node-exporter
  namespace: monitoring
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`k3s-master.home`) && PathPrefix(`/node-exporter`)
      kind: Rule
      services:
        - name: prometheus-node-exporter
          port: 9100
